name: Explore all factors

on:
  push:
    branches:
      - all_factors
  pull_request:
    branches:
      - all_factors

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build the Docker image
        run: |
          docker build -t asso .

      - name: Run the Docker image
        run: |
          docker run --rm asso > results.csv

      - name: Commit and push results
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "github-actions@github.com"
          git add results.csv
          git commit -m "Docker update results"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}