name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build the Docker image
        run: |
          docker build -t asso .

      - name: Run tests (if applicable)
        run: |
          docker run --rm asso

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: results
          path: results.txt